version: '3'

services:
  postgres:
    image: postgres:14.3
    restart: always
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root
    container_name: pantrydb
    volumes:
      - ./postgres:/var/lib.postgresql/data
